#
# Welcome to Jekyll!
#

title: Stacked Heaps
author: Kiran Thorat
description: >- # this means to ignore newlines until "baseurl:"
  Heaps of insights, stacked for the curious minds.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social
github_username: k-thorat
stackoverflow_username: k-thorat
linkedin_username: kiranthorat

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-email-protect

sass:
  quiet_deps: true
  silence_deprecations: [import]

# How post links are created
permalink: /:title/

# Exclude from processing.
exclude:
  - Playground/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
